import {
  PencilSquareIcon,
  IdentificationIcon,
} from "@heroicons/react/20/solid";
import { Metadata } from "next";
import "../../../types";

const url =
  "https://virtserver.swaggerhub.com/MIROAGUSTIN11/api-cultivar/0.1/routines";

export const metadata: Metadata = {
  title: "POKEMON APP",
  description: "Generated by create next app",
};
export function PokemonList({ id, name, sprites, base_experience }: Pokemon) {
  const foto =
    "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60";

  return (
    <ul
      role="list"
      className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3 pt-5"
    >
      {results.map((data) => (
        <li
          key={data.id}
          className="col-span-1 divide-y divide-gray-200 rounded-lg bg-white shadow"
        >
          <div className="flex w-full items-center justify-between space-x-6 p-6">
            <div className="flex-1 truncate">
              <div className="flex items-center space-x-3">
                <h3 className="truncate text-sm font-medium text-gray-900">
                  {data.name}
                </h3>
                <span className="inline-flex flex-shrink-0 items-center rounded-full bg-green-50 px-1.5 py-0.5 text-xs font-medium text-green-700 ring-1 ring-inset ring-green-600/20">
                  {data.especie}
                </span>
              </div>
              <p className="mt-1 truncate text-sm text-gray-500">
                {data.nombre}
              </p>
            </div>
            <img
              className="h-10 w-10 flex-shrink-0 rounded-full bg-gray-300"
              src={foto}
              alt=""
            />
          </div>
          <div>
            <div className="-mt-px flex divide-x divide-gray-200">
              <Link
                to={`/routines/detail/${data.id}`}
                className="relative -mr-px inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-bl-lg border border-transparent py-4 text-sm font-semibold text-gray-900"
              >
                <div className="flex w-0 flex-1">
                  <IdentificationIcon
                    className="h-5 w-5 text-gray-400 mx-5"
                    aria-hidden="true"
                  />
                  Detalles
                </div>
              </Link>
              <Link
                to={`/routines/${data.id}/edit`}
                className="relative inline-flex w-0 flex-1 items-center justify-center gap-x-3 rounded-br-lg border border-transparent py-4 text-sm font-semibold text-gray-900"
              >
                <PencilSquareIcon
                  className="h-5 w-5 text-gray-400 mx-5"
                  aria-hidden="true"
                />
                <div className="-ml-px flex w-0 flex-1 mx-5">Editar</div>
              </Link>
            </div>
          </div>
        </li>
      ))}
    </ul>
  );
}
